### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by nozense** [gsobell/dango#1]
Trying to run this, it tries to install gnugo every time and then clears the screen leaving me with:

> dango.sh: 88: Syntax error: "do" unexpected (expecting ";;")

OT: This is a great project! Keep it up!

**Comment by gsobell** [comment]
Thank you very much @uhtoom! I would have never found this, as I added this script to my `$PATH` and already installed `gnugo`.  I know from a previous project that a script that is `curl`ed and piped directly into `sh` can be problematic, since it's not interactive; though that shouldn't cause a problem here.

Here are my preliminary findings:

| | Run from `$PATH` | `curl`ed from GitHub |
 | --- | --- |---|
|`gnugo` installed | Runs without errors. |`dango.sh: line 88: syntax error near unexpected token ;; dango.sh: line 88: select rules in Japanese Chinese; do;; `
|`gnugo` not installed | Successfully installs 'gnugo', then `/home/$USER/Documents/Repos/dango/dango.sh: line 88: syntax error near unexpected token ;;' /home/$USER/Documents/Repos/dango/dango.sh: line 88: select rules in Japanese Chinese; do;; '` |  Successfully installs `gnugo`, then runs without errors. |

This behavior is a bit strange, even spooky, and not sure what to make of it. There are no obvious syntax errors in the script upon brief inspection.

**Comment by nozense** [comment]
Can confirm! Everything seems to work a lot better when the script is in $PATH - except, in my case, the play-again option goes to trying to install gnugo again, finding it already installed and then exiting with the "See you!" dialog (=
My bash knowledge is far to rudimentary to try and help with this I'm afraid! (=

**Comment by gsobell** [comment]
Commit 79b2907 seems to have fixed this.
